title: kimjeyoun
description: >-
  kimjeyoun's portfolio.
url: "https://kimjeyoun.github.io"
github: kimjeyoun
email: wodbs5602@naver.com
google_analytics: <YOUR UA TOKEN>

exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: ChemistryX/hyde-comments
  issue-term: pathname

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
